### ISSUE TITLE
The flexible docking results cannot be correctly identified by PyMOL

### ISSUE THREAD

**Issue by supernova4869** [PKUGaoGroup/DSDPFlex#2]
I used flexible docking to generate protein-ligand complex. However, the phenyl rings in DSDP_out.pdbqt were incorrectly identified by PyMOL (see the uploaded files). When using DSDP_redock, this problem does not occur.
![docking results](https://github.com/user-attachments/assets/c6504a35-b9c3-44ee-840f-04bcd47f5524)
![addH](https://github.com/user-attachments/assets/4f72d376-e87c-4b22-8691-1dc5086f4e62)
The docking result was also uploaded: [DSDP_out.zip](https://github.com/user-attachments/files/17411152/DSDP_out.zip)

**Comment by PKUGaoGroup** [comment]
Both DSDP_redocking and DSDPFlex do not change the atom type and molecular topology during the docking. You can find that the input and output ligand pdbqt files have the same atom types. Please check your input pdbqt has the right atom type and use a right way to add hydrogens.

**Comment by PKUGaoGroup** [comment]
Both DSDP_redocking and DSDPFlex do not change the atom type and molecular topology during the docking. You can find that the input and output ligand pdbqt files have the same atom types. Please check your input pdbqt has the right atom type and use a right way to add hydrogens.

**Comment by supernova4869** [comment]
Thank you. I have compared both systems and checked my initial structures, and found that after optimization of my initial structure, the docking output becomes correct.
