### ISSUE TITLE
DSDP  didn't find valid solutions

### ISSUE THREAD

**Issue by zj-liu** [PKUGaoGroup/DSDPFlex#4]
Sometimes DSDPFlex gives this output error. How should one change the settings? Autodock Vina flexible docking can run and output docking poses.

`DSDP didn't find valid solutions. Check the settings.
: Numerical result out of range`

**Comment by HCAya** [comment]
Hi! Could you provide your input files and command? This error means it encountered some numerical issue, which is probably caused by improper command.

**Comment by zj-liu** [comment]
These are my input files. [1owe_protein.zip](https://github.com/user-attachments/files/17972028/1owe_protein.zip)
- `1owe_ligand.pdbqt` is the ligand file, processed with Meeko from the file`1owe_ligand.sdf` in PDBbind.
- `1owe_protein_rigid.pdbqt`  and `1owe_protein_flex.pdbqt` are the protein files, processed with Meeko from the file `1owe_protein.pdb` in PDBbind with hydrogen added and water removed.

The command is 
`./DSDPflex --ligand 1owe_ligand.pdbqt --protein 1owe_protein_rigid.pdbqt --flex 1owe_protein_flex.pdbqt --box_min 10.1 3.4 19.9 --box_max 35.1 28.4 44.9 --exhaustiveness 512 --search_depth 40 --top_n 5`

**Comment by HCAya** [comment]
One potential issue I found is that some of the selected side chains are far from the pocket and may be out of the box. If a side chain is positioned outside the box, there will always be an out-of-box penalization which can impede the optimization.

Please try selecting only the necessary side chains around the pocket and make sure the box is large enough, then see if the program works.

**Comment by zj-liu** [comment]
Thanks for your reply. The program now works.

**Comment by zj-liu** [comment]
And the output of DSDPFlex only contains the ligand poses, while Vina flexible docking also gives the corresponding side chain conformation. Can DSDP also output the flexible side chain coordinates?

**Comment by HCAya** [comment]
The flexible side chain output is specified by `--out_flex`
please provide a valid file path.

**Comment by zj-liu** [comment]
Thanks a lot for your answer.
